import { Text } from 'pixi.js';
import { Fonts } from './theme';
import { textStyle } from './text';

/** Font Awesome 6 Free code points (solid unless noted). */
export const Icons = {
    play: '',
    pause: '',
    stop: '',
    next: '',
    prev: '',
    forward: '',
    gear: '',
    search: '',
    heart: '',
    download: '',
    arrowLeft: '',
    chevronLeft: '',
    chevronRight: '',
    chevronDown: '',
    chevronUp: '',
    anglesLeft: '',
    anglesRight: '',
    close: '',
    music: '',
    shuffle: '',
    refresh: '',
    retry: '',
    list: '',
    star: '',
    check: '',
    info: '',
    warning: '',
    error: '',
    volumeHigh: '',
    volumeLow: '',
    volumeMute: '',
    desktop: '',
    keyboard: '',
    mouse: '',
    globe: '',
    wrench: '',
    brush: '',
    gamepad: '',
    expand: '',
    compress: '',
    folderOpen: '',
    trash: '',
    signOut: '',
    home: '',
    film: '',
    user: '',
    trophy: '',
    clock: '',
    circle: '',
    bars: '',
    disc: '',
    bolt: '',
    bell: '',
    sliders: '',
    image: '',
    headphones: '',
    dice: '',
    sort: '',
    filter: '',
    eye: '',
    eyeSlash: '',
    fileImport: '',
    upload: '',
    circlePlay: '',
    circleNotch: '',
    codeBranch: '',
    link: '',
    crown: '',
    fire: '',
    skull: '',
    feather: '',
    question: '',
    external: '',
    palette: '',
    bug: '',
    flask: '',
    magic: '',
    hand: '',
    plus: '+',
    minus: '',
    rotate: '',
    tachometer: '',
    microchip: '',
    cubes: '',
    database: '',
    lightbulb: '',
    eraser: '',
} as const;

export type IconName = keyof typeof Icons;

export function icon(name: IconName, size = 16, color = 0xffffff, regular = false): Text {
    const t = new Text({
        text: Icons[name],
        style: textStyle({
            font: regular ? Fonts.iconRegular : Fonts.iconSolid,
            weight: regular ? '400' : '900',
            size,
            color,
            align: 'center',
        }),
    });
    t.anchor.set(0.5);
    t.eventMode = 'none';
    return t;
}
